import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Cabecalho from '@/components/Cabecalho'
import Rodape from '@/components/Rodape'
import Button from '@/components/Button'
import Input from '@/components/Input'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Minhas Séries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Cabecalho/>

        <div className={styles.body}>

          <div className={styles.capa}>
            <div className={styles.subcapa}>

              <div className={styles.info}>
                <h1>Bem Vindo(a)</h1>
                <h2>Explore suas séries favoritas</h2>
              </div>

              <div className={styles.busca}>
                <Input
                  style={{width: '950px', height: '30px'}} 
                  type={'text'} 
                  placeholder={'Buscar por uma série..'}
                ></Input>

                <Button
                  style={{width: '100px', height: '30px'}}
                >Buscar</Button>

              </div>
            </div>
          </div>

          <div>

          </div>

        </div>

        <Rodape/>
      </main>

    </>
  )
}
